version:  '3.7'
services: 
    mydb:
        restart: always
        image: postgres
        ports: 
            - 5432:5432
        environment: 
            POSTGRES_DB: test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres